alias ll="ls -alF"
alias la="ls -A"
alias l="ls -CF"

alias preview="/Applications/Preview.app/Contents/MacOS/Preview"
alias vlc="/Applications/VLC\ ƒ/VLC.app/Contents/MacOS/VLC"

alias frozencemetery@ellis="ssh -p 61150 frozencemetery@gsilbis.dnsalias.net"
alias ellis="ssh -p 61150 frozencemetery@gsilvis.dnsalias.net"
alias littlegreenmen="ssh rharwood@b.armory.com"
alias boogeyman="ssh rharwood@b.armory.com"
alias b="ssh rharwood@b.armory.com"
alias magikarp="ssh frozencemetery@jakehaas.com"
alias admin@magikarp="ssh admin@jakehaas.com"
alias frozencemetery@magikarp="ssh frozencemetery@jakehaas.com"
alias overcode="ssh frozencemetery@overcode.dyndns-remote.com"
alias frozencemetery@overcode="ssh frozencemetery@overcode.dyndns-remote.com"
alias admin@overcode="ssh administrator@overcode.dyndns-remote.com"
alias frovercode="ssh frozencemetery@overcode.dyndns-remote.com"
alias admovercode="ssh administrator@overcode.dyndns-remote.com"
alias slocal="ssh robbie@192.168.0.13"
alias csa3="ssh rharwood@csa3.bu.edu"
alias csa2="ssh rharwood@csa2.bu.edu"
alias zapdos="ssh frozencemetery@zapdos.jakehaas.com"
alias admin@zapdos="ssh administrator@zapdos.jakehaas.com"
alias administrator@zapdos="ssh administrator@zapdos.jakehaas.com"
alias frozencemetery@zapdos="ssh frozencemetery@zapdos.jakehaas.com"

alias al="sl -a"

alias ssup="/var/lib/gems/1.8/bin/sup"
alias sup="~robbie/.getmail/script.sh && /var/lib/gems/1.8/bin/sup"
