--- 
- !masanjin.net,2006-10-01/Redwood/Maildir 
  uri: maildir:/home/robbie/mail/bu/
  usual: true
  archived: false
  id: 1
  labels: []

- !masanjin.net,2006-10-01/Redwood/Maildir 
  uri: maildir:/home/robbie/mail/earthlink/
  usual: true
  archived: false
  id: 2
  labels: []

- !masanjin.net,2006-10-01/Redwood/Maildir 
  uri: maildir:/home/robbie/mail/gmail/
  usual: true
  archived: false
  id: 3
  labels: []

- !masanjin.net,2006-10-01/Redwood/Maildir 
  uri: maildir:/home/robbie/mail/hotmail
  usual: true
  archived: false
  id: 4
  labels: []

